name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SBCL
        run: sudo apt-get install -y sbcl
      - name: Run tests
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp
          sbcl --noinform \
               --load quicklisp.lisp \
               --eval "(ql:quickload :acc)" \
               --eval "(fiveam:run-all-tests)" \
               --quit
